### ISSUE TITLE
I can't use plenv from your repo

### ISSUE THREAD

**Issue by dolmen** [mikkoi/git-mailmap#2]
The file `.perl-version` contains « `git-hooks-5.16.2` ».
My [`plenv`](https://github.com/tokuhirom/plenv/) can't work with that.

So if building requires a special environment, it would be helpful to document it in a [CONTRIBUTING.pod file](https://github.com/blog/1184-contributing-guidelines).
Or better, just remove `.perl-version` from the repository.

**Comment by mikkoi** [comment]
Removed. Thank you for the suggestion.
